#!/bin/bash

# Variables, Paths, Version
repeat=1
VN="0.4.1"  # Version Number
leetpath="$(dirname "$(readlink -f "$0")")"  # Path of LeetFolder
leetdiff="LeetSpeakEasy.py" # Default leetspeak difficulty

# ASCII art for the cool kids
function asciilogo {
echo '
 ____________ ________________________  ___________ _________ _________
/_   \_____  \\_____  \______  \      \ \_   _____//   _____//   _____/
 |   | _(__  <  _(__  <   /    /   |   \ |    __)_ \_____  \ \_____  \ 
 |   |/       \/       \ /    /    |    \|        \/        \/        \
 |___/______  /______  //____/\____|__  /_______  /_______  /_______  /
            \/       \/               \/        \/        \/        \/ 
Version '$VN'						   By: BrohdeXC
-----------------------------------------------------------------------'
}

# Tool Selection for the nerds
function asciimain {
echo '    1) Leet a Word
    2) Leet a List
    3) Leet w/ CeWL (By Robin Wood AKA Digininja)
    4) Append Wordlists
    5) Permutate Wordlists
    6) Options
    7) Exit
-----------------------------------------------------------------------'
    read -p 'Please make a selection: ' choice
}

# Leetspeak Difficulty Selection
function asciidiff {
    echo "    1) UL Case - Onlyt and lowercase substitutions (Fastest)
    2) Easy   - Common single letter substitutions (Default)
    3) Medium - Uncommon single letter substitutions
    4) Hard   - All possible leetspeak substitutions (Slow, Long List)
    5) Return

                Currently Selected: "$leetdiff"
-----------------------------------------------------------------------"
    read -p "Which leetspeak list would you like to use? (1-5) " diffchoice
}

# Main Function 
function main {
    while [[ $repeat -eq 1 ]]; do
        clear
	asciilogo
	asciimain
        # User selection of which program to run
        if (($choice == 1)); then
	    clear
	    asciilogo
            wordleet
            repeat
        elif (($choice == 2)); then
	    clear
	    asciilogo
            listleet
            repeat
        elif (($choice == 3)); then
	    clear
	    asciilogo
            cewlleet
            repeat
	elif (($choice == 4)); then
	    clear
	    asciilogo
            append
            repeat
        elif (($choice == 5)); then
	    clear
	    asciilogo
            permutate
            repeat
        elif (($choice == 6)); then
	    diff
	elif (($choice == 7)); then
	    echo Thanks for using 1337ness!
	    sleep .75
	    clear
            repeat=0
        else
            echo "Invalid Response, Please make a selection (1-7): "
        fi
    done
}

# LeetSpeak Difficulty
function diff {
    diffchoice=0
    while [[ $diffchoice != 5 ]]; do
        clear
        asciilogo
        asciidiff
        if (($diffchoice == 1)); then
            leetdiff="UpperLower.py"
        elif (($diffchoice == 2)); then
            leetdiff="LeetSpeakEasy.py"
        elif (($diffchoice == 3)); then
            leetdiff="LeetSpeakMedium.py"
	elif (($diffchoice == 4)); then
	    leetdiff="LeetSpeakHard.py"
        elif (($diffchoice == 5)); then
            return
        else
            echo "Invalid Response, Please make a selection (1-5): "
        fi
    done
}

# Repeat Function
function repeat {
    read -p "Would you like to continue? (y/n): " cont
    if [[ $cont == "y" || $cont == "Y" ]]; then
        echo "Continuing..."
	sleep .75
        return 0
    elif [[ $cont == "n" || $cont == "N" ]]; then
        echo "Thanks for using 1337ness!"
	sleep 0.75
	clear
        repeat=0
        return 1
    else
        echo "Invalid Response, Would you like to continue? (y/n): "
        return 0
    fi
}

# WordLeet Function
function wordleet {
	read -p "What is the word you would like to 1337? " word
	read -p "What is the name of the output file? " out
	python3 $leetpath/$leetdiff $word > $out
	echo Wordlist saved as $out
}

# ListLeet Function
function listleet {
	read -p "What is the path of the input file? " input
	read -p "What is the name of the output file? " out
	while read line
	do
		python3 $leetpath/$leetdiff $line >> $out
	done < $input
	echo Wordlist saved as $out
}

# CewlLeet Function
function cewlleet {
	# Gather information to be used
	read -p "What is the URL you would like to scrape? " url
	read -p "What is the minimum word length to look for? " min
	read -p "What is the maximum word length to look for? " max
	read -p "How many of the most common words should be used? " count
	read -p "What do you want to name the output file? " out

	# Run Cewl and output it to a file
	cewl -m $min -x $max -d 0 -w $out --lowercase $url 

	# Take the [user defined #] most common words and put them in a temporary file
	cat $out | head -n $count > temp.txt
	rm $out

	# Take the [user defined #] most common words and put them into a list 
	echo -------------------------------------------------------------------------
	echo The top $count words on this website are:
	cat temp.txt | head -n $count
	echo -------------------------------------------------------------------------

	# Create output file put the leetspeak variations into it
	touch $out
	while read line
	do
		python3 $leetpath/$leetdiff $line >> $out
	done < temp.txt

	echo Your wordlist has been generated as \"$out\"!

	# Clean up
	rm temp.txt
}

# Append List Function
function append {
        # Get user Inputs
        read -p "What is the name of the first list? " lst1
        read -p "What is the name of the second list? " lst2
        read -p "What is the name of the output file? " out

        # Combine the lists into one output file
        cat $lst1 $lst2 > $out
        echo Lists appended into \"$out\"!
}
 
# Permutate List Function
function permutate {
        read -p "What is the name of the first list? " lst1
        read -p "What is the name of the second list? " lst2
        read -p "What is the name of the output file? " out

        touch "$out"

    # Generate permutations
    while read line1
        do
        while read line2
            do
            echo $line1$line2 >> "$out"
        done < "$lst2"
    done < "$lst1"

    echo "Permutations saved to \"$out\"!"
}

main
